### ISSUE TITLE
漏扫界面颜色

### ISSUE THREAD

**Issue by Ershu1** [ggg4566/BurpBountyPlus#2]
我想问一下，漏扫界面蓝色是代表无危害，红色代表存在漏洞的吧？

**Comment by ggg4566** [comment]
对的，蓝色代表无害其他颜色都代表有问题

**Comment by Ershu1** [comment]
> 对的，蓝色代表无害其他颜色都代表有问题

还有个小问题就是扫描的时候logger多了，会卡住，无法显示

**Comment by ggg4566** [comment]
> > 对的，蓝色代表无害其他颜色都代表有问题
> 
> 还有个小问题就是扫描的时候logger多了，会卡住，无法显示

更新了下，你重新下载再试试，我这边五六千条日志暂时不卡

**Comment by Ershu1** [comment]
> > > 对的，蓝色代表无害其他颜色都代表有问题
> > 
> > 
> > 还有个小问题就是扫描的时候logger多了，会卡住，无法显示
> 
> 更新了下，你重新下载再试试，我这边五六千条日志暂时不卡

嗯嗯，可以，不像之前那样了
