### ISSUE TITLE
Cant Import

### ISSUE THREAD

**Issue by Huibuh2010** [ggg4566/BurpBountyPlus#4]
Hello, this extension looks really nice but i cant import.

what do i wrong? thx
![Unbenannt](https://user-images.githubusercontent.com/83202082/146178046-86430a3b-64e3-48d4-9a87-74f42b4ff2dc.PNG)

**Comment by ggg4566** [comment]
There is no problem with the latest version, BurpSuite 2021.10 and jdk 12.  which version are you using?
