### ISSUE TITLE
发起扫描后logger中没有请求，用的burp2021.10 java11

### ISSUE THREAD

**Issue by yshdxm** [ggg4566/BurpBountyPlus#7]
![微信图片_20220402023331](https://user-images.githubusercontent.com/54091599/161322020-575f007f-f0be-42cc-afe7-514bbe4444ac.png)
burp的主动扫描正常，但是插件这边没有看到请求
![image](https://user-images.githubusercontent.com/54091599/161322107-1e077e73-36b0-4430-910f-be5d84f30ccc.png)
而且我加载了漏洞配置文件后，插件显示名字是空白的
![image](https://user-images.githubusercontent.com/54091599/161322175-84c1c30c-d7c4-49e9-b2af-81cf092b7f75.png)

**Comment by yshdxm** [comment]
配置文件名字是空白的
![image](https://user-images.githubusercontent.com/54091599/161322281-8cae785a-b020-40a1-b563-6639091919a8.png)

**Comment by ggg4566** [comment]
把profile加上
