### ISSUE TITLE
Profiles are blankl

### ISSUE THREAD

**Issue by jakre1234** [ggg4566/BurpBountyPlus#8]
Hello, when loading the profiles, the profiles are loaded but they appear completely blank. Not sure what's going on.

![burpbountyplusError](https://user-images.githubusercontent.com/89703702/196202623-df5bde72-2cdf-48e0-b6d5-ffe87a4e59c4.png)

**Comment by ggg4566** [comment]
> Hello, when loading the profiles, the profiles are loaded but they appear completely blank. Not sure what's going on.
> 
> ![burpbountyplusError](https://user-images.githubusercontent.com/89703702/196202623-df5bde72-2cdf-48e0-b6d5-ffe87a4e59c4.png)
You can manually create a new profile  to check if it can be loaded successfully.

**Comment by jakre1234** [comment]
Hey @ggg4566 ,On creating a new profile, it works fine. I am using this repo to load up the profileshttps://github.com/six2dez/burp-bounty-profiles
Can you suggest some more recently updated profile list.

Thanks and Regards,

**Comment by jakre1234** [comment]
Thanks @ggg4566 , seems like it was issue with profiles I was loading from https://github.com/six2dez/burp-bounty-profiles . Mind sharing your preferred profile list, also you can close the issue? 

Thanks and Regards,
